{{- $route := .Values.route -}}
{{- $service_port := .Values.service.port -}}
{{- if $route.create -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
  {{- with $route.annotations }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "pacman.labels" . | indent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ $route.host }}
  path: /{{ include "app.urlPath" . | trimPrefix "/" | trimSuffix "/" }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "pacman.fullname" . }}
    weight: 100
  {{- if $route.tls.enabled }}
  tls:
    {{- if $route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ $route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if $route.tls.termination }}
    termination: {{ $route.tls.termination }}
    {{- end }}
  {{- end }}
{{- end -}}