apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: pacman-namespace
  name: pacman 
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: pacman 
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # %