apiVersion: v1
kind: Service
metadata:
  namespace: pacman-namespace
  labels:
    name: mongo
  name: mongo
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
