name: 'Login to azure container registry'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ContainerRegistry:
    name: 'Push docker image to Azure container registry'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
    runs-on: ubuntu-latest
    environment: Test
    # Steps represent a sequence of tasks that will be executed as part of the job
    
    defaults:
      run:
        shell: bash
      
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_NAME }}
          username: ${{ secrets.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}
          
      - name: 'Build and push docker image to azure registry'
        working-directory: ./docker
        run: |
            docker build . -t ${{ secrets.CONTAINER_NAME }}/jesus/pacman-nodejs-app:latest
            docker push ${{ secrets.CONTAINER_NAME }}/jesus/pacman-nodejs-app:latest
