name: 'Login to azure container registry'

on:

  workflow_dispatch:

jobs:
  ContainerRegistry:
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash
      
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://52.165.248.195:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              kv/azure username | AZURE_VAULT_USERNAME;

      - name: "Login to Azure CLI and Azure Container Registry"
        run: |	
          az login -u $AZURE_VAULT_USERNAME -p ${{ secrets.AZURE_SECRET_PASSWORD }}
          az acr login --name ${{ secrets.CONTAINER_NAME }}

      - name: 'Build and push docker image to azure registry'
        working-directory: ./docker
        run: |
            docker build . -t ${{ secrets.CONTAINER_NAME }}/jesus/pacman-nodejs-app:latest
            docker push ${{ secrets.CONTAINER_NAME }}/jesus/pacman-nodejs-app:latest
